development:
  host: localhost
  database: easydrill_development

test:
  host: localhost
  database: easydrill_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOLAB_URI'] %>
